name: app
description: "Real-time Analysis & Detection Area Rawan Jentik"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.2.2
  flutter_secure_storage: ^10.2.0
  geolocator: ^14.0.1
  image_picker: ^1.2.3
  latlong2: ^0.9.1
  open_file: ^4.0.0
  path_provider: ^2.1.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/33.02_kelurahan.geojson
    - .env
